### ISSUE TITLE
[FEAT] Patch march=native for older generation x86-64 processors.

### ISSUE THREAD

**Issue by MastaG** [linuxserver/docker-unrar#4]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The makefile from the unrar source sets the following:
```
# Linux using GCC
CXX=c++
CXXFLAGS=-march=native -O2 -std=c++11 -Wno-logical-op-parentheses -Wno-switch -Wno-dangling-else
LIBFLAGS=-fPIC
DEFINES=-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DRAR_SMP
STRIP=strip
AR=ar
LDFLAGS=-pthread
DESTDIR=/usr
```

The Dockerfile only adds ```-static``` to the LDFLAGS.
However ```-march=native``` is causing issues on haswell generation hardware.
The binary will sometimes segfault with an invalid opcode.
This is probably due to the host being used to build the images having a more recent processor supporting avx2 and/or sse4.x.

Perhaps you could patch this flag to make it run on generic x86-64 hardware.
Something like:
```sed -i 's|CXXFLAGS=-march=native|CXXFLAGS=-march=x86-64 -mtune=generic|' ```

I believe both the alpine 3.19 and Ubuntu Jammy OS have x86-64 as their default OS target.

### Reason for change

I'm getting sefaults when the unrar binary is being called by sabnzbd.

### Proposed code change

Add ```sed -i 's|CXXFLAGS=-march=native|CXXFLAGS=-march=x86-64 -mtune=generic|' ``` to the Dockerfile.

**Comment by thespad** [comment]
So my main question here is what impact it has on performance for newer CPUs if we change it from native. I don't really want to hobble a bunch of systems if I can avoid it, but equally we don't want to break a load of older ones either.

**Comment by MastaG** [comment]
I don't think "native" is very useful here, because the container image is most likely compiled from within a CI/CD pipeline and then pushed to towards the repository for public usage.
So in this case it would take the architecture of the processor from the pipeline runner.
Imo it would be best to match the architecture of the base image which in this case are Alpine 19 and Ubuntu Jammy.
If I'm not mistaken they're both x86-64 generic distros.
Ubuntu does have an experimental x86-64-v3 23.04 distro but it's only for testing purposes and I couldn't find any information on the Alpine website where they state that a specific generation of x86 cpus are required.

**Comment by MastaG** [comment]
Thank you. Will this automatically bump this image 
 and sabnzbd ?

**Comment by aptalca** [comment]
This image is built and pushed. As per sab and others that pull in unrar, the next time they build, they will include the new unrar. But this change won't trigger an automatic rebuild for them. Let me know which image and tag you are using and I can manually trigger a new build

**Comment by MastaG** [comment]
I'm using lscr.io/linuxserver/sabnzbd:latest.

**Comment by aptalca** [comment]
Building: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-sabnzbd/detail/master/620/pipeline

**Comment by Sundeep81** [comment]
Hi, 

This change seems to have broken unrar on my Synology that is running on an INTEL Atom D2700 for the Alpine 3.19 image. 

I am also using the lscr.io/linuxserver/sabnzbd:latest image. 

When I try and manual unrar from within the container I get the following error: 
> Illegal instruction (core dumped)

after rebuilding unrar without the following line, the issue was resolved
`sed -i 's|CXXFLAGS=-march=native|CXXFLAGS=-march=x86-64-v2|' makefile`

**Comment by MastaG** [comment]
Perhaps the atom is v1 then?

Op wo 13 mrt 2024 18:43 schreef Sundeep Balsara ***@***.***>:

**Comment by thespad** [comment]
It's a 13 year old CPU so most likely.

**Comment by aptalca** [comment]
> after rebuilding unrar without the following line, the issue was resolved

The line is not the issue.
You're building on your (old) machine so yes, it would work. But we build on our new builders. If we built on our new machines without that line, it wouldn't work on your old machine, and it wouldn't work on a lot of even newer machines. That line provides backwards compatibility for machines that are up to about 10 years old. But your machine is still older.

**Comment by MastaG** [comment]
Personally I don't mind if unrar would be built for the oldest generation of x86-64 cpu's.
I don't have any numbers but I don't think sse3/4 or avx2 would optimize for unpacking speed.
And even if it takes a few seconds longer then so be it.
This is a very popular repository so I'd say just shoot for the best compatibility.

**Comment by aptalca** [comment]
The number of folks running these on 10+ yr old cpus is quite small.
Don't underestimate people's desire to save a few seconds. So many people try to set up hardlinks just so they can do atomic moves.

Also, the feature that needs the newer capabilities was newly added to unrar 7 and did not exist in 6. If upstream added a new feature, we'd like to include/enable it.

For folks on old hw, we have a mod: https://github.com/linuxserver/docker-mods/tree/universal-unrar6

**Comment by Sundeep81** [comment]
Thanks Everyone,

Not sure if this helps but I tried building on my old machine with 

`CXXFLAGS=-march=native|CXXFLAGS=-march=x86-64-v2`

and Unrar gives me the error I stated above.  

However when I rebuild using the following:

`CXXFLAGS=-march=native|CXXFLAGS=-march=x86-64`

Everything works as expected.

**Comment by Safihre** [comment]
@animetosho Since you worked on the unrar SIMD code a bit: does unrar not include a mechanism that prevents newer instructions to be skipped on older architectures? Like you implemented in sabctools.

**Comment by animetosho** [comment]
> does unrar not include a mechanism that prevents newer instructions to be skipped on older architectures?

In this specific case, the new instructions are specifically being added by the compiler, so there's nothing unrar can do about it.

unrar does have runtime CPU detection (like sabctools), so you don't need to compile for a specific CPU. In other words, completely removing the `-march` parameter makes the most sense as it provides the greatest compatibility. If the CPU supports newer features, unrar will automatically use them.

**Comment by Safihre** [comment]
> unrar does have runtime CPU detection (like sabctools), so you don't need to compile for a specific CPU. In other words, completely removing the `-march` parameter makes the most sense as it provides the greatest compatibility. If the CPU supports newer features, unrar will automatically use them.

With `-march` removed, compilers will not optimized by adding commands that are unsupported on older platforms?
That seems like a nice quick-fix @MastaG and @thespad!

EDIT: So remove the `CXXFLAGS=-march=native` that unrar automatically adds.

**Comment by thespad** [comment]
I believe the default in current gcc is `x86-64` (which is also `x86-64-v1`) if you don't provide a `march`.

The question is what, if any, performance hit is there from not optimising for any CPU instructions added in the last 15 years?

**Comment by Safihre** [comment]
Unrar has implemented manual optimizations for the critical parts of the code. Which are activated at runtime, based on feature detection. 
So I would be surprised if there's much more a compiler can do for the critical path.

**Comment by animetosho** [comment]
> The question is what, if any, performance hit is there from not optimising for any CPU instructions added in the last 15 years?

The only way to really know is to test it out.

Having said that, I'd be surprised if you noticed any performance difference.

**Comment by sanderjo** [comment]
I created a few different unrar binaries on Ubuntu 22.04 on a i3-1115G4 (with AVX512, FWIW), with unrar make like

`make clean && make 'CXXFLAGS=-march=x86-64-v2'`

Resulting binaries:

```
$ ll unrar.*
-rwxrwxr-x 1 sander sander 421232 mrt 18 14:38 unrar.march_native*
-rwxrwxr-x 1 sander sander 587064 mrt 18 14:49 unrar.march_x86-64*
-rwxrwxr-x 1 sander sander 587064 mrt 18 15:00 unrar.march_x86-64-v2*
-rwxrwxr-x 1 sander sander 421232 mrt 18 14:40 unrar.no_march_native*
```

I created a 1GB file with random info, and created a rar set with 100MB rar files.

Unpacking: all the same time: 2.5 - 3.5 seconds

I then created a password protected rar set, and then there are time differences:

```
$ rm myfile ; time ./unrar.march_native x -pSECRET  *01.rar >/dev/null

real	0m2,088s
user	0m1,480s
sys	0m0,636s
```

```
$ rm myfile ; time ./unrar.no_march_native x -pSECRET  *01.rar >/dev/null

real	0m2,113s
user	0m1,506s
sys	0m0,694s
```



```
$ rm myfile ; time ./unrar.march_x86-64-v2 x -pSECRET  *01.rar >/dev/null

real	0m4,975s
user	0m5,606s
sys	0m0,585s
```

And unrar 6 is even slower:
```
$ rm myfile ; time unrar613/unrar/unrar x -pSECRET  *01.rar >/dev/null

real	0m6,717s
user	0m6,002s
sys	0m0,604s
```

Conclusion:
* plain rar: no big difference with unrar 7 with different march options
* passworded rar: quite big time differences

**Comment by sanderjo** [comment]
Another approach could be:

LSIO bundles unrar 7 for modern CPU / OS, and unar 7 (or 6?) for older CPU / OS, in the same docker image

SABnzbd could determine if modern unrar 7 works, and if not, fall back to the non-optimized unrar 7 /6 so that old CPU / OS is still handled (although slower)

**Comment by animetosho** [comment]
That's a surprising result; I wasn't able to reproduce though. Tested on an AVX-512 enabled 12700K, with both GCC 12 and Clang 13.  
Not a strictly controlled test, but I couldn't eyeball any speed differences outside error.  
Also had a quick look at the decryption ASM under march=native, but didn't notice anything that'd likely have much of an effect.

If you want to investigate your build, remove the `strip` command in the Makefile, and run under `perf record`. After the run, use `perf report` to see the profile. That should give an idea of where the slowdown is occurring (assuming it's in one place).

For >=AVX2 targets (x86-64-v3), you might get some minor boosts from AVX and BMI, but I wouldn't expect much. unrar's code isn't exactly highly optimised though, which makes it a little harder to reason about.

**Comment by thespad** [comment]
For context what I'm trying to balance here is providing support for a reasonable age of hardware without hobbling performance for people with new kit.

I don't have a problem in principle with compiling against x86-64-v1 as long as it's not going to have a significant impact; for the number of users affected and the age of the hardware in question it really needs to be basically no difference to make it worthwhile.

**Comment by animetosho** [comment]
Just supplying my opinion, for whatever it's worth: usage of `-march` needs to be well justified. I don't think anyone has presented any *actual* benefits of x86-64-v2.  
Vague statements over performance are meaningless when there's nothing to actually back those up. On the other hand, compatibility is demonstrably impacted.

**Comment by thespad** [comment]
We could remove `-march` entirely (it's set to `native` in the makefile, which is what caused the original issues), which would be equivalent to `x86-64` (or `x86-64-v1`).

**Comment by MastaG** [comment]
Yeah just remove the ```march``` entirely.
Then we get to use the gcc defaults, which should be x86-64 (v1).
So until gcc decides to 'up' the defaults we're all good.
For the record I've already upgraded my hardware so the original issue doesn't apply to me any longer.

**Comment by Safihre** [comment]
@thespad Let's do that :)

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-unrar/pull/6

**Comment by Safihre** [comment]
Thank you, this helps us a lot with a the support questions!
Having you, as the Docker experts, provide and maintain the SABnzbd Docker saves us a lot of hassle!
